server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.shang.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcolud-provider-dept
  datasource:
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001

info:
  app.name: shang-springcloudprovider
  company.name: shang

